VitoVan/calm

- .github/workflows/main.yml
- scripts/dist.sh
> fix: `before_canvas.lisp` was not correctly loaded in distribution

- .github/workflows/main.yml
- README.md
- calm
- scripts/dist.sh
- scripts/gen-macos-app.sh
> feat: calm dist --fancy-name MyCustomAppName

- .github/workflows/main.yml
- scripts/dist.sh
- scripts/install.sh
> feat: add ICON to Windows process

- README.md
- sh/fedora/pack.sh
remove unnecessary files when zipping CALM on Linux
> fix zipping calm on linux

- build/build.bat
- sh/msys/pack.sh
> win: remove the flashing console by default

- .github/workflows/calm.yml
- calm.asd
- sh/darwin/pack.sh
https://github.com/libsdl-org/SDL/issues/1625
> fedora: upgrade SDL2 version

- examples/meditator/canvas.lisp
- src/utils.lisp
sdl2-mixer:playing is not working for music play
> remove garbage code.

- src/utils.lisp
make uiop:run-program interactively
> fix Homebrew installation

- README.md
- calm.asd
- docs/installation.md
- s/dev/darwin/pack.sh
- src/calm.c
I'd better never write C again.
> fix mystery Windows bug (I'm the fool)

- .github/workflows/calm.yml
- .github/workflows/example-circles.yml
- .github/workflows/example-fan.yml
- .github/workflows/example-meditator.yml
- .github/workflows/example-mondrian.yml
- build/build.sh
- src/c.lisp
previously it's 2.35, this fixes https://github.com/VitoVan/calm/issues/67
> downgrade the dependency of glibc to 2.33

- .github/workflows/calm.yml
- calm.asd
- src/c.lisp
/fix https://github.com/VitoVan/calm/issues/130
> fix: audio won't play the second time

- entry.lisp
this could cause big problem on recent Linux
> fix: remove unnecessary load of systems

- s/usr/linux/init-msg.sh
- src/calm.c
> use calm.core right after it was created

- .github/workflows/calm.yml
- s/usr/macos/dmg.lisp
> ci: fix macos-13 create-dmg applescript

- README.md
- README_JA.md
I created Japanese translated README.
> Add Japanese README

- README_JA.md
Updated README_JA.md to be the same as the original.
> doc: update README_JA.md

- s/usr/all/fonts.conf
> disable font scanning from cwd

- README.md
- README_JA.md
Discord server: [![Discord](https://img.shields.io/discord/1124894601908584528?logo=discord&logoColor=white&label=Chat&labelColor=%235865f2&color=white)](https://discord.gg/xN6VeaMr2a)
> doc: replace version badge with chat badge

- docs/hacking_JA.md
- docs/installation_JA.md
I have added Japanese versions of the following two files!
* docs/hacking.md
* docs/installation.md
> doc: add Japanese documents

- README.md
- README_JA.md
- s/usr/linux/appimage.lisp
- s/usr/macos/bundle.lisp
- s/usr/windows/installer.lisp
this option should not be changed while
calling `publish-with-options`, so let's
not offer it.
> remove unnecessary option while publishing

- build/build.sh
- entry.lisp
- s/README.md
- s/dev/all/alive.sh
- s/dev/all/install-alive.lisp
- s/dev/all/load-calm.lisp
- s/dev/all/start-alive.lisp
- s/usr/all/panic.lisp
- src/calm.c
https://github.com/nobody-famous/alive
The corresponding VSCode configuration:
```json
{
"telemetry.telemetryLevel": "off",
"alive.lsp.startCommand": [
"calm",
"alive"
]
}
```
/fix #168
> feat: add alive support

- src/calm.c
> win: to coexist with other SDL2

- .github/workflows/calm.yml
- s/dev/darwin/pack.sh
- s/usr/macos/dmg.lisp
- src/utils.lisp
> fix: publish-with-options with spaced app-name

- build/build.sh
> remove Windows fonts dir on *nix
